# Generated by Django 6.0.3 on 2026-08-01 18:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('discovered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Vantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Rung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('loopback', 'Loopback'), ('gateway', 'Gateway'), ('isp_hop', 'ISP hop'), ('isp_dns', 'ISP resolver'), ('public_dns', 'Public DNS'), ('anchor', 'Distant anchor')], max_length=16)),
                ('host', models.GenericIPAddressField(protocol='IPv4')),
                ('label', models.CharField(max_length=64)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rungs', to='trail.trail')),
            ],
            options={
                'ordering': ('depth', 'host'),
            },
        ),
        migrations.AddField(
            model_name='trail',
            name='vantage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trails', to='trail.vantage'),
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fired_at', models.DateTimeField()),
                ('prober', models.CharField(blank=True, default='', max_length=64)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='trail.trail')),
                ('vantage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='trail.vantage')),
            ],
            options={
                'ordering': ('fired_at',),
            },
        ),
        migrations.CreateModel(
            name='Probe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtt_ms', models.FloatField(blank=True, null=True)),
                ('sent', models.PositiveIntegerField(default=1)),
                ('received', models.PositiveIntegerField(default=0)),
                ('loss_pct', models.FloatField(default=0.0)),
                ('ttl', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.CharField(blank=True, default='', max_length=200)),
                ('rung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probes', to='trail.rung')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probes', to='trail.sample')),
            ],
            options={
                'ordering': ('rung__depth', 'rung__host'),
                'constraints': [models.UniqueConstraint(fields=('sample', 'rung'), name='uniq_probe_per_sample_rung')],
            },
        ),
        migrations.AddIndex(
            model_name='rung',
            index=models.Index(fields=['trail', 'depth'], name='trail_rung_trail_i_bcb2b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='rung',
            constraint=models.UniqueConstraint(fields=('trail', 'host'), name='uniq_rung_per_trail_host'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['trail', 'fired_at'], name='trail_sampl_trail_i_04cb4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='sample',
            constraint=models.UniqueConstraint(fields=('trail', 'fired_at'), name='uniq_sample_per_trail_tick'),
        ),
    ]
