# Generated by Django 6.0.3 on 2026-08-01 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rung',
            name='kind_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rung',
            name='label_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rung',
            name='kind',
            field=models.CharField(choices=[('loopback', 'Loopback'), ('gateway', 'Gateway'), ('home_router', 'Home router'), ('isp_hop', 'ISP hop'), ('isp_dns', 'ISP resolver'), ('public_dns', 'Public DNS'), ('anchor', 'Distant anchor')], max_length=16),
        ),
        migrations.CreateModel(
            name='ProberControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('interval_seconds', models.PositiveIntegerField(default=30)),
                ('timeout_seconds', models.FloatField(default=2.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_sweep_at', models.DateTimeField(blank=True, null=True)),
                ('pid', models.PositiveIntegerField(blank=True, null=True)),
                ('hostname', models.CharField(blank=True, default='', max_length=128)),
                ('last_error', models.CharField(blank=True, default='', max_length=300)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('trail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controls', to='trail.trail')),
                ('vantage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='control', to='trail.vantage')),
            ],
            options={
                'ordering': ('vantage__name',),
            },
        ),
    ]
